# Generated by Django 2.1.1 on 2019-06-26 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190626_1757'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarsReviews',
        ),
    ]
