# Generated by Django 2.1.1 on 2019-06-26 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_carsreviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='reviews',
            field=models.IntegerField(default=0, verbose_name='Всего отзывов'),
        ),
    ]
