# Generated by Django 2.2.2 on 2019-06-23 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, null=True, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.CreateModel(
            name='Cupboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cupboard', models.IntegerField(verbose_name='Номер шкафа')),
            ],
            options={
                'verbose_name': 'Шкаф',
                'verbose_name_plural': 'Шкафы',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, null=True, verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Имя')),
                ('phone', models.CharField(blank=True, max_length=12, verbose_name='Номер телефона')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
            ],
            options={
                'verbose_name': 'Читатель',
                'verbose_name_plural': 'Читатели',
            },
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelf', models.IntegerField(verbose_name='Номер полки')),
            ],
            options={
                'verbose_name': 'Полка',
                'verbose_name_plural': 'Полки',
            },
        ),
        migrations.CreateModel(
            name='ShelfPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelfplace', models.IntegerField(verbose_name='Номер полки')),
            ],
            options={
                'verbose_name': 'Номера на полках',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, null=True, verbose_name='Название тега')),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Название книги')),
                ('published_date', models.DateTimeField(verbose_name='Дата публикации')),
                ('get_date', models.DateTimeField(auto_now_add=True, verbose_name='Книга выдана')),
                ('expire_date', models.DateTimeField(auto_now_add=True, verbose_name='Сдать до')),
                ('isfree', models.BooleanField(default=True, verbose_name='В наличии')),
                ('author', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='books.AuthorsList', verbose_name='Автор')),
                ('cupboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_cupboard', to='books.Cupboard', verbose_name='Номер шкафа')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Genre', verbose_name='Жанр')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_place', to='books.ShelfPlace', verbose_name='Номер места на полке')),
                ('reader', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='books.Reader', verbose_name='Читатель')),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_shelf', to='books.Shelf', verbose_name='Номер полки')),
                ('tags', models.ManyToManyField(to='books.Tags', verbose_name='Название тега')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
    ]
