# Generated by Django 2.2.2 on 2019-06-23 05:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='expire_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Сдать до'),
        ),
        migrations.AlterField(
            model_name='books',
            name='get_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Книга выдана'),
        ),
    ]
