# Generated by Django 2.2.2 on 2019-06-23 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20190623_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='reader',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='books.Reader', verbose_name='Читатель'),
        ),
    ]
