# Generated by Django 2.2 on 2019-06-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='player',
            field=models.ManyToManyField(blank=True, through='game.PlayerGameInfo', to='game.Player'),
        ),
    ]
