# Generated by Django 2.2 on 2019-06-28 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20190628_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='', upload_to='img/%Y/%m/%d/', verbose_name='ФОТО'),
        ),
    ]
