# Generated by Django 2.1.1 on 2019-06-26 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_car_reviews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Автомобиль', 'verbose_name_plural': 'Автомобили'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.RemoveField(
            model_name='car',
            name='reviews',
        ),
    ]
